after-login-command = []
after-startup-command = []
start-at-login = true
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true
accordion-padding = 90
default-root-container-layout = 'tiles'
default-root-container-orientation = 'horizontal'
key-mapping.preset = 'qwerty'
[gaps]
inner.horizontal = 16
inner.vertical =   16
outer.left =       16
outer.bottom =     16
outer.top =        16
outer.right =      16
[workspace-to-monitor-force-assignment]
    "Communication" = ['main']
    "AI-LM-Studio" = ['main']
    "Terminal" = ['main']
    "Development" = ['main']
    "Nix-Darwin" = ['main']
    "Browser" = ['main']
    "1st-Workspace" = ['secondary']
    "2nd-Workspace" = ['secondary']
    "3rd-Workspace" = ['secondary']
    "4th-Workspace" = ['secondary']
    "5th-Workspace" = ['secondary']
[mode.main.binding]
alt-enter = 'exec-and-forget open -na /Applications/Ghostty.app'
alt-slash = 'layout tiles horizontal vertical'
alt-comma = 'layout accordion horizontal vertical'
alt-h = 'focus --boundaries-action wrap-around-the-workspace left'
alt-left = 'focus --boundaries-action wrap-around-the-workspace left'
alt-j = 'focus --boundaries-action wrap-around-the-workspace down'
alt-down = 'focus --boundaries-action wrap-around-the-workspace down'
alt-k = 'focus --boundaries-action wrap-around-the-workspace up'
alt-up = 'focus --boundaries-action wrap-around-the-workspace up'
alt-l = 'focus --boundaries-action wrap-around-the-workspace right'
alt-right = 'focus --boundaries-action wrap-around-the-workspace right'
alt-shift-h = 'move left'
alt-shift-left = 'move left'
alt-shift-j = 'move down'
alt-shift-down = 'move down'
alt-shift-k = 'move up'
alt-shift-up = 'move up'
alt-shift-l = 'move right'
alt-shift-right = 'move right'
alt-t = 'workspace "Terminal"'
alt-d = 'workspace "Development"'
alt-x = 'workspace "Nix-Darwin"'
alt-c = 'workspace "Communication"'
alt-b = 'workspace "Browser"'
alt-1 = 'workspace "1st-Workspace"'
alt-2 = 'workspace "2nd-Workspace"'
alt-3 = 'workspace "3rd-Workspace"'
alt-4 = 'workspace "4th-Workspace"'
alt-5 = 'workspace "5th-Workspace"'
alt-shift-t = 'move-node-to-workspace "Terminal"'
alt-shift-d = 'move-node-to-workspace "Development"'
alt-shift-x = 'move-node-to-workspace "Nix-Darwin"'
alt-shift-c = 'move-node-to-workspace "Communication"'
alt-shift-b = 'move-node-to-workspace "Browser"'
alt-shift-1 = 'move-node-to-workspace "1st-Workspace"'
alt-shift-2 = 'move-node-to-workspace "2nd-Workspace"'
alt-shift-3 = 'move-node-to-workspace "3rd-Workspace"'
alt-shift-4 = 'move-node-to-workspace "4th-Workspace"'
alt-shift-5 = 'move-node-to-workspace "5th-Workspace"'
alt-shift-f = 'layout floating tiling'
alt-shift-equal = 'balance-sizes'
alt-tab = 'workspace-back-and-forth'
alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'
alt-shift-semicolon = 'mode service'
alt-shift-r = 'mode resize'
[[on-window-detected]]
if.app-id = 'app.zen-browser.zen'
if.window-title-regex-substring = 'Picture-in-Picture'
run = ['layout floating']
[mode.resize.binding]
h = 'resize width -50'
j = 'resize height +50'
k = 'resize height -50'
l = 'resize width +50'
b = 'balance-sizes'
minus = 'resize smart -50'
equal = 'resize smart +50'
enter = 'mode main'
esc = 'mode main'
[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main'] # Reset layout
f = ['layout floating tiling', 'mode main'] # Toggle between floating and tiling layout
backspace = ['close-all-windows-but-current', 'mode main']
alt-shift-h = ['join-with left', 'mode main']
alt-shift-j = ['join-with down', 'mode main']
alt-shift-k = ['join-with up', 'mode main']
alt-shift-l = ['join-with right', 'mode main']
