preload = ~/.wallpapers/wallhaven-l3mool.jpg

# Set the wallpaper for all monitors
wallpaper = ,~/.wallpapers/wallhaven-l3mool.jpg

# Enable splash text rendering over the wallpaper
splash = false

# Fully disable ipc
ipc = off
