# See https://wiki.hyprland.org/Configuring/Monitors/
# List current monitors and resolutions possible: hyprctl monitors
# Format: monitor = [port], resolution, position, scale

# Source custom monitor configuration
source = ~/.config/hypr/custom.monitors.conf
