## The maximum number of lines the interface should take up
## Set it to 0 to always go full screen
inline_height = 0

## Defaults to true. If enabled, upon hitting enter Atuin will immediately execute the command. Press tab to return to the shell and edit.
# This applies for new installs. Old installs will keep the old behaviour unless configured otherwise.
enter_accept = true

