return {
  {
    "LazyVim/LazyVim",
    opts = function()
      vim.filetype.add({
        extension = {
          tf = "terraform",
          tfvars = "terraform",
          tftest = "terraform",
          hcl = "hcl",
          j2 = "jinja",
          jinja = "jinja",
          jinja2 = "jinja",
          ps1 = "ps1",
          psm1 = "psm1",
          psd1 = "ps1",
          tcl = "tcl",
          glsl = "glsl",
          vert = "glsl",
          frag = "glsl",
          sql = "sql",
          toml = "toml",
        },
        filename = {
          ["terraform.tfvars"] = "terraform",
          [".terraform.lock.hcl"] = "hcl",
          [".tflint.hcl"] = "hcl",
          ["terragrunt.hcl"] = "hcl",
          ["Dockerfile"] = "dockerfile",
          ["docker-compose.yml"] = "yaml.docker-compose",
          ["docker-compose.yaml"] = "yaml.docker-compose",
          ["compose.yml"] = "yaml.docker-compose",
          ["compose.yaml"] = "yaml.docker-compose",
          ["ansible.cfg"] = "dosini",
          [".ansible-lint"] = "yaml",
          [".yamllint"] = "yaml",
          [".zshrc"] = "zsh",
          [".bashrc"] = "bash",
          [".bash_profile"] = "bash",
          [".zshenv"] = "zsh",
          ["Makefile"] = "make",
          ["makefile"] = "make",
          ["flake.lock"] = "json",
        },
        pattern = {
          [".*/playbooks/.*%.ya?ml"] = "yaml.ansible",
          [".*/roles/.*/tasks/.*%.ya?ml"] = "yaml.ansible",
          [".*/roles/.*/handlers/.*%.ya?ml"] = "yaml.ansible",
          [".*/ansible/.*%.ya?ml"] = "yaml.ansible",
          [".*playbook.*%.ya?ml"] = "yaml.ansible",
          [".*k8s.*%.ya?ml"] = "yaml.kubernetes",
          [".*/kubernetes/.*%.ya?ml"] = "yaml.kubernetes",
          [".github/workflows/.*%.ya?ml"] = "yaml.github-actions",
          ["%.gitlab%-ci%.ya?ml"] = "yaml.gitlab-ci",
          ["docker%-compose.*%.ya?ml"] = "yaml.docker-compose",
          [".*cloudformation.*%.ya?ml"] = "yaml.cloudformation",
          [".*%.j2"] = "jinja",
          [".*%.jinja2?"] = "jinja",
          [".*%.sh%.j2"] = "sh",
        },
      })
    end,
  },
}
